### ISSUE TITLE
Reporters don't work in NodeJS

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-nodejs#13]
We've noticed during TADHack that it is not possible to sync an Observer running in the Browser with a Reporter running in Node.

We suspect it is related with Object.observe not being supported with last versions of Node. Older versions should work. 

Can you confirm, pls?

**Comment by jboulmal** [comment]
I confirm that @pchainho Object.observe()  has been DEPRECATED and is available by default in Node >= 0.11.13.. However, we can try some modules  to tackle that [ Object.observe](https://github.com/aheckmann/observed)

**Comment by jboulmal** [comment]
soon @pchainho will have problem in browser also. 
``In November 2015 it was announced that Object.Observe was being withdrawn from TC39. It has been deprecated from Chrome 49`` [chrome-49-deprecations](https://developers.google.com/web/updates/2016/02/chrome-49-deprecations). Besides, also firefox [discourages](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/observe) its usage.

**Comment by pchainho** [comment]
It is not supported anymore in chrome but we are using this [polyfill](https://www.npmjs.com/package/object.observe) and it works fine with browsers. It is supposed to also work fine with nodejs

**Comment by jboulmal** [comment]
In this case, we don't have much choices. We will use polyfill as well in node.

**Comment by jboulmal** [comment]
The [polyfill](https://github.com/MaxArt2501/object-observe) gives an error in node >= v6.9.1.
```(node:8450) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3): [object Object]```
While retracting back to older version of node(v0.10.40) doesn't support promise :
`    return new Promise(function (resolve, reject) {
               ^
ReferenceError: Promise is not defined
`

**Comment by jboulmal** [comment]
The Promise is not a problem any more for node v0.10.40 (and older). However, I got strange error 
```
DescriptorURL: http://catalogue.hybroker.rethink.ptinovacao.pt/.well-known/runtime/Runtime
Error:  [TypeError: Object http://catalogue.hybroker.rethink.ptinovacao.pt/.well-known/runtime/Runtime has no method 'includes']
runtime core exited.
```

**Comment by jboulmal** [comment]
Ongoing also here [Syncher: Replace O.o() by Proxy](https://github.com/reTHINK-project/dev-service-framework/issues/35)......

**Comment by jboulmal** [comment]
Hi, 
It is not an easy task to debug a problem in the service-framework and core-runtime since we are using dist/ folders everywhere.  
We have `Response timeout` fired from the `Message_BUS`, because the message does not reach SyncherManager. https://github.com/reTHINK-project/dev-runtime-core/blob/master/src/syncher/SyncherManager.js#L72 and https://github.com/reTHINK-project/dev-runtime-core/blob/9f267f1862e8a1d97f6e558cd732405e4358bf47/src/bus/Bus.js#L153

**Comment by jboulmal** [comment]
Besides, when running an `Observer` hyperty on `Runtime Node` and a `Reporter` on `Runtime-Browser`, we get the same `Response Timeout!`. However, the Hyperty is still responsive for incoming connections.

![](https://cloud.githubusercontent.com/assets/15377466/21258658/4f72b90a-c37e-11e6-8756-16946949d639.png)

**Comment by pchainho** [comment]
This should be fixed [here](https://github.com/reTHINK-project/dev-service-framework/tree/dev-proxy-observe). Now pending on [this](https://github.com/reTHINK-project/dev-runtime-core/issues/149).

**Comment by pchainho** [comment]
Working fine with Mutual Authentication disabled
