### ISSUE TITLE
Update with Runtime develop

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-nodejs#17]
At least the following has to be done:

- [x] requireHyperty(): add new optional parameter `reuseAddress` -> check runtimeUA.loadHyperty(..) new attribute that is used to set if Hyperty addresses are to be reused .
- [x] create sandboxes according to runtime capabilities. -> have a look [here](https://github.com/reTHINK-project/dev-hyperty-toolkit/tree/develop/resources/factories)

**Comment by jboulmal** [comment]
done here [ commit Update with Runtime Develop ](https://github.com/reTHINK-project/dev-runtime-nodejs/commit/5863a5531699e97bafafb338eba81835d178e3c3)
