### ISSUE TITLE
Nodejs bundle

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-nodejs#18]
the nodejs runtime files should be bundled in a single file eg `rethink4node.js` that could  be served from some rethink server or installed as a node module

**Comment by jboulmal** [comment]
Not sure to understand what you mean @pchainho ? do you mean dist/ folder like runtime-browser ?

**Comment by pchainho** [comment]
yes, you can put it in a dist folder but what is important is to have a single file, probably already transpiled

**Comment by jboulmal** [comment]
Do you have an example for me @pchainho  ?

**Comment by pchainho** [comment]
I guess you can have a look on how other dev repos are doing including the browser runtime

**Comment by jboulmal** [comment]
please @pchainho comment status on this ?
