### ISSUE TITLE
Node Module for the runtime and Docker image for Apps

### ISSUE THREAD

**Issue by pchainho** [reTHINK-project/dev-runtime-nodejs#20]
As defined by WP6, all back-end components should be deployable with docker images

**Comment by pchainho** [comment]
As discussed in Aveiro with @vitormsilva , the runtime nodejs should be a node module independent of the App ie we should not have eg the conference server demo in this node module.

Then, the Apps themselves will have their own docker images including the runtime nodejs module. 

We should give priority to this one in order to have a first release.

**Comment by jboulmal** [comment]
done @pchainho
